spring:
  application:
    name: gateway-service

server:
  port: 8001

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmty: 0

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    sss-api-service:
    path: /sss-rest-services/**
    url: http://localhost:8300/restapi/sample